name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: "Showing TEST env variable"
        run: echo "$TEST"
        env:
          TEST: dev
      - name: Build Android Release for dev env
        run: |
          cd android && ./gradlew assembleRelease
        env:
          TEST: dev
      - name: Upload Artifact for dev ENV
        uses: actions/upload-artifact@v1
        with:
          name: dev-app-release.apk
          path: android/app/build/outputs/apk/release/
      
      - name: "Showing TEST env variable"
        run: echo "$TEST"
        env:
          TEST: dev    
      - name: Build Android Release for prod env
        run: |
          cd android && ./gradlew assembleRelease
        env:
          TEST: prod
      - name: Upload Artifact for prod env
        uses: actions/upload-artifact@v1
        with:
          name: prod-release.apk
          path: android/app/build/outputs/apk/release/          
